apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dn080w71c-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dn080w71c-dotnet-basic-gitops