apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dn080w71c-dotnet-basic
  janus-idp.io/tekton: dn080w71c-dotnet-basic
  backstage.io/kubernetes-id: dn080w71c-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dn080w71c-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
